name: BUILD

on:
  push:
    branches: [ action ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Install Node.js
        uses: actions/setup-node@v2-beta
        with:
          node-version: v14.19.0
      - name: install, build
        run: |
          yarn
          yarn react-build
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          # Artifact name
          name: dist
          # A file, directory or wildcard pattern that describes what to upload
          path: |
            build/*
